package model;

public class GameRuleException extends RuntimeException {

  // Generated by eclipse
  private static final long serialVersionUID = 4479730135239559098L;

  public GameRuleException(String message) {
    super(message);
  }
}
